version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: dpp-postgres
    restart: always
    environment:
      POSTGRES_USER: kenny
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: my_project_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 